title: Andrea Fagerman
logo: headshot.png
description: "Howdy, ya'll! As a former teacher and recent graduate, I am a lover of all things learning and have truly learned the value of numbers. If you're curious to learn more about me, please feel free to reach out through my [LinkedIn!](https://www.linkedin.com/in/andrea-fagerman-817317193)"
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme 
